Increase the MSRV for Corrosion to 1.46
Recently all CI builds using rust 1.44.1 have been failing on CI with the
following error message:
```
error: failed to get `cargo_metadata` as a dependency of package `corrosion-generator v0.1.0 (/home/runner/work/corrosion/corrosion/generator)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  error reading from the zlib stream; class=Zlib (5)
CMake Error at cmake/Corrosion.cmake:427 (message):
  corrosion-generator failed: 101
Call Stack (most recent call first):
  test/cpp2rust/CMakeLists.txt:1 (corrosion_import_crate)
  ```

  The relevant issue is probably
  https://github.com/rust-lang/cargo/issues/8258.

Starting with cargo 1.46 the CI failures are resolved